on: pull_request_review
name: Add a label to approved pull request
jobs:
  labelWhenApproved:
    name: Add label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals and add label
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: '2'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADD_LABEL: 'Ready to Merge'
          REMOVE_LABEL: 'Needs Review'
